#!/bin/bash


sudo apt install git && git clone https://github.com/Deodutt/algo.git

sudo apt update && sudo apt upgrade
sudo apt-get update && sudo apt-get install -y \
build-essential \
libssl-dev \
libffi-dev \
python3-dev \
python3-setuptools \
pip \
python3-venv

python3 -m venv venv
