#!/bin/bash

sudo apt update
sudo apt upgrade

sudo apt-get update && sudo apt-get install \
build-essential \
libssl-dev \
libffi-dev \
python3-dev \
python3-setuptools \
pip \
python3-venv

cd ..
python3 -m venv venv
