#!/bin/bash

sudo apt update && sudo apt upgrade
sudo apt install git && git clone https://github.com/Deodutt/algo.git
sudo apt-get install python3-pip
sudo apt-get install python3-venv

cd algo
sudo apt-get update && sudo apt-get install \
build-essential \
libssl-dev \
libffi-dev \
python3-dev \
python3-setuptools \

cd ..
python3 -m venv venv

cd venv ; source ./bin/activate
cd ..
cd algo
python3 -m pip install -U pip virtualenv && python3 -m pip install -r requirements.txt